### PR TITLE
primitive addition of enterprise stuff by copy-paste

### PR DESCRIPTION
**Pull request by gwenshap**
I don't think that copy-paste is the right way to add control-center support :) Let me know what you planned for enterprise and I'll rework it.

### CODE REVIEW

**Comment by ewencp** [comment]
@gwenshap Just source the original and we can include it under a different name in the enterprise version? Or use the `Makefile` to "build" the enterprise version as a concatenation of the oss and non-oss version? Or just maintain it all in one script and have that script fail gracefully if you try to use an enterprise feature when only the oss bits are available? I think we need things to fail gracefully anyway since if you run from debs/rpms, you might not have all the components installed.

**Comment by gwenshap** [comment]
yeah, I like the one-script and fail-nicely idea. Less mess packaging and it nicely advertises extra features. It is just that we had two directories, so I figured we wanted to keep it separate.

**Comment by ewencp** [comment]
well, i'm guessing it was just setup that way since we didn't have a specific plan, but i'll leave the final say up to the original architect @kkonstantine :)

**Comment by kkonstantine** [comment]
@ewencp gave an extensive list of all the options. I was thinking about it too, and I agree with both of you that the 3rd option of graceful failure in the absence of control-center (when COS) is the best now.

**Comment by gwenshap** [comment]
Taking it out for now since C3 is changing stuff around its config files and defaults.

**Pull request closed without merging**
