### PR TITLE
CP-503: Add version command

### PR DESCRIPTION
**Pull request by kkonstantine**

### CODE REVIEW

**Comment by rhauch** [comment]
@kkonstantine can you provide a sample of the usage and output? It's nice to be able to output the version for each service, but wouldn't it also be useful to just say `confluent version` and see the version for each component rather than just the CP version?

**Comment by kkonstantine** [comment]
Returns the global confluent flavor and version as well as a service specific version. 

Examples: 

- Enterprise: 
```bash
$ confluent version
Confluent Enterprise: 4.1.0
```
- Open Source: 
```bash
$ confluent version
Confluent Open Source: 4.1.0
```
- Kafka version: 
```bash
$ confluent version kafka
1.1.0
```
- Zookeeper version: 
```bash
$ confluent version zookeeper
3.4.10
```
- Other services version:
```bash
$ confluent version connect
4.1.0
```

**Comment by kkonstantine** [comment]
@rhauch you are faster than your shadow sometimes. I was editing exactly this message

**Comment by kkonstantine** [comment]
Thanks!

**Pull request merged**
